// Indonesian-only, context-aware responses based on keywords

// Expanded Indonesian keyword responses - 50+ topics
const ID_RESPONSES = {
  // Emosi & Perasaan
  galau: "Merasa galau adalah pengalaman manusiawi yang wajar, terutama ketika menghadapi situasi yang kompleks atau penuh ambiguitas. Perasaan ini menunjukkan bahwa Anda sedang memproses sesuatu yang penting. Berikut cara mengelolanya dengan sehat:\n\n1. Terima tanpa judgment. Galau bukan kelemahan, melainkan tanda bahwa Anda peduli dan berpikir mendalam. Jangan paksa diri untuk 'segera baik'.\n\n2. Journaling untuk clarity. Tulis apa yang membuat Anda galau tanpa sensor. Terkadang keraguan terlihat lebih jelas saat di tuangkan dalam kata-kata.\n\n3. Talk to someone you trust. Sharing dengan teman yang tidak menghakimi bisa memberikan perspektif baru. Jangan isolasi diri saat galau.\n\n4. Distract dengan aktivitas ringan. Baca buku, dengarkan musik, atau jalan-jalan sebentar untuk 'reset' pikiran.\n\n5. Set a decision deadline. Jika galau karena harus memilih, beri diri waktu terbatas untuk memutuskan, lalu commit dengan pilihan tersebut.\n\n6. Practice self-compassion. Bicara pada diri sendiri seperti Anda berbicara pada teman baik yang sedang galau.\n\nIngat, galau adalah sementara. Like clouds, it will pass.",
  sedih: "Kesedihan adalah emosi yang valid dan bagian penting dari pengalaman manusia. Tidak ada yang salah dengan merasa sedih - ini menunjukkan kapasitas Anda untuk merasakan kedalaman emosi. Berikut cara menavigasinya:\n\n1. Allow yourself to feel. Jangan tahan atau invalidasi kesedihan Anda. Air mata dan rasa sedih adalah cara tubuh melepaskan beban emosional.\n\n2. Identify the source. Apa yang sebenarnya membuat Anda sedih? Kehilangan? Kekecewaan? Kesepian? Mengetahui akarnya membantu proses healing.\n\n3. Create a comfort routine. Siapkan 'emotional first aid kit': playlist favorit, film comfort, makanan hangat, atau aktivitas yang menenangkan.\n\n4. Reach out. Kesendirian memperburuk kesedihan. Hubungi satu orang yang Anda percaya, meski hanya untuk duduk diam bersama.\n\n5. Physical movement helps. Light exercise, yoga, atau sekadar jalan kaki bisa melepaskan endorphin dan mengurangi intensitas kesedihan.\n\n6. Seek professional help if needed. Jika kesedihan berkepanjangan dan mengganggu fungsi sehari-hari, konsultasi dengan psikolog adalah langkah berani dan bijak.\n\nIt's okay not to be okay. Healing takes time.",
  senang: "Senang mendengar Anda merasa senang! Nikmati momen ini sepenuhnya dan bagikan kebahagiaan Anda dengan orang-orang terdekat. Momen positif layak untuk dirayakan.",
  marah: "Kemarahan adalah emosi yang powerful dan seringkali menandakan bahwa sesuatu yang penting bagi Anda telah dilanggar. Penting untuk mengelolanya dengan sehat agar tidak merusak relasi atau diri sendiri:\n\n1. Pause before reacting. Amarah dalam 6 detik pertama biasanya reaktif, bukan responsif. Tarik napas, keluar dari situasi sejenak sebelum bereaksi.\n\n2. Identify the trigger. Apa yang sebenarnya membuat Anda marah? Apakah itu disrespect, injustice, atau feeling powerless? Mengerti akarnya membantu.\n\n3. Express assertively, not aggressively. Gunakan 'I statements': 'Saya merasa... ketika... karena...' daripada menyalahkan atau menyerang.\n\n4. Physical outlet yang sehat. Olahraga intens, punching bag, atau bahkan teriakan di tempat sepi bisa melepaskan energi amarah tanpa konsekuensi negatif.\n\n5. Pick your battles. Tidak semua hal layak diperjuangkan dengan amarah. Tanyakan: 'Apakah ini penting 1 minggu dari sekarang?'\n\n6. Channel into action. Gunakan energi amarah untuk change yang konstruktif, bukan destructive. Amarah bisa menjadi fuel untuk activism atau improvement.\n\n7. Forgiveness is for you. Memaafkan bukan berarti membenarkan kesalahan, melainkan melepaskan beban amarah agar Anda bisa move forward.\n\nAnger is one letter short of danger. Manage it wisely.",
  cemas: "Kecemasan adalah respons alami terhadap perceived threat atau uncertainty, tapi ketika berlebihan bisa mengganggu kualitas hidup. Berikut strategi evidence-based untuk mengelolanya:\n\n1. Grounding techniques (5-4-3-2-1 method). Identifikasi 5 hal yang Anda lihat, 4 yang Anda sentuh, 3 yang Anda dengar, 2 yang Anda cium, 1 yang Anda rasakan. Ini membawa Anda kembali ke present moment.\n\n2. Breathing exercises. Selain 4-7-8, coba box breathing: 4 detik inhale, 4 hold, 4 exhale, 4 hold. Repeat 5 kali.\n\n3. Challenge anxious thoughts. Tanyakan: 'Apa buktinya?' 'Apakah ini fact atau interpretation?' 'Apa yang paling buruk yang bisa terjadi, dan bisakah saya handle itu?'\n\n4. Limit stimulants. Kafein, gula berlebihan, dan lack of sleep memperburuk kecemasan. Perhatikan lifestyle factors.\n\n5. Scheduled worry time. Alih-alih cemas sepanjang hari, alokasikan 15 menit khusus untuk 'worry'. Di luar waktu itu, tulis saja dan 'tunda' ke waktu tersebut.\n\n6. Progressive muscle relaxation. Tegangkan dan relaksasikan setiap grup otot dari ujung kaki ke kepala. Ini melepaskan physical tension yang menyertai kecemasan.\n\n7. Seek professional support. CBT (Cognitive Behavioral Therapy) terbukti sangat efektif untuk anxiety disorders.\n\nAnxiety is like a rocking chair - it gives you something to do but doesn't get you anywhere.",
  bosan: "Saat bosan, cobalah hal baru yang sederhana: jalan-jalan singkat di sekitar rumah, baca buku yang sudah lama tidak dibaca, atau coba resep masakan baru. Perubahan kecil bisa membawa semangat baru.",
  lelah: "Istirahatlah sejenak. Tubuh dan pikiran Anda butuh pemulihan. Tidur yang cukup sangat penting untuk kesehatan fisik dan mental. Prioritaskan istirahat sebagai bagian dari produktivitas.",
  stress: "Stres bisa melelahkan baik fisik maupun mental. Identifikasi sumber stres Anda dan lakukan langkah kecil untuk menguranginya. Teknik relaksasi seperti meditasi atau yoga bisa membantu.",
  takut: "Rasa takut adalah mekanisme perlindungan alami. Coba identifikasi sumber ketakutan Anda dan hadapi secara bertahap. Berbicara dengan orang yang dipercaya juga bisa membantu meringankan beban.",
  malas: "Rasa malas terkadang menandakan tubuh butuh istirahat. Namun jika berkepanjangan, coba pecah tugas besar menjadi langkah kecil yang lebih mudah dikerjakan. Mulai dari yang paling sederhana.",
  kecewa: "Kekecewaan adalah bagian dari hidup. Izinkan diri Anda merasakannya, tetapi jangan terlalu lama terjebak di sana. Evaluasi apa yang bisa dipelajari dan fokus pada langkah selanjutnya.",
  bingung: "Kebingungan sering terjadi saat dihadapkan pada banyak pilihan. Coba buat daftar pro-kontra, konsultasikan dengan orang yang berpengalaman, atau beri diri Anda waktu untuk berpikir dengan jernih.",
  kesepian: "Kesepian adalah perasaan yang valid. Cobalah bergabung dengan komunitas atau grup yang memiliki minat serupa, atau hubungi teman lama yang sudah lama tidak Anda kontak.",
  iri: "Rasa iri terkadang muncul tanpa disadari. Alihkan fokus dari orang lain ke diri sendiri. Ingat, setiap orang punya perjalanan dan waktunya masing-masing.",
  cinta: "Cinta adalah perasaan yang indah namun kompleks. Jaga komunikasi yang jujur, saling menghormati, dan memberi ruang untuk masing-masing tumbuh. Hubungan sehat butuh usaha dari kedua belah pihak.",
  putus: "Putus cinta memang menyakitkan. Beri diri Anda waktu untuk berduka dan pulih. Jangan buru-buru melupakan, tapi jangan juga terjebak di masa lalu. Fokus pada perawatan diri dan pertumbuhan pribadi.",

  // Kesehatan & Wellness
  sehat: "Menjaga kesehatan tubuh adalah foundation untuk performa optimal dalam segala aspek hidup. Ini rekomendasi praktis yang terbukti secara ilmiah:\n\n1. Move your body daily. Tidak harus gym - jalan kaki 30 menit, naik turun tangga, atau stretching saat break sudah beneficial. Yang penting konsisten, bukan intensitas.\n\n2. Prioritize sleep hygiene. 7-9 jam tidur berkualitas memulihkan otak dan tubuh. Hindari screen 1 jam sebelum tidur, jadikan kamar gelap dan dingin, dan hindari kafein setelah jam 2 sore.\n\n3. Nutrition over diet. Fokus pada whole foods (sayur, protein, healthy fats, complex carbs) daripada menghitung kalori obsesif. 80/20 rule: 80% nutritious, 20% whatever you want.\n\n4. Hydration matters. 8 gelas sehari membantu fungsi otak, energi, dan kulit. Bawa botol kemana-mana dan minum sebelum haus.\n\n5. Mental health affects physical health. Stress kronis bisa menyebabkan sakit fisik. Praktikkan mindfulness, meditasi, atau journaling untuk mental well-being.\n\n6. Preventive care penting. Check-up rutin, vaksinasi, dan screening sesuai usia bisa deteksi masalah sebelum parah. Jangan tunggu sakit untuk peduli kesehatan.\n\n7. Listen to your body. Fatigue, sakit kepala terus-menerus, atau mood swing bisa jadi tanda tubuh butuh rest atau evaluasi lifestyle.\n\nHealth is wealth - tanpa kesehatan, segala achievement terasa hollow.",
  sakit: "Saat tubuh sakit, itu adalah sinyal bahwa sistem Anda butuh perhatian dan pemulihan. Menghormati sinyal ini adalah bentuk self-care yang penting:\n\n1. Prioritaskan istirahat total. Tubuh membutuhkan energy untuk fight infection atau healing. Jangan paksa bekerja dengan performa rendah - itu justru memperpanjang waktu sakit.\n\n2. Hydration adalah key. Cairan yang cukup membantu mengeluarkan toxin, menjaga suhu tubuh, dan mencegah dehidrasi yang bisa memperburuk kondisi.\n\n3. Nutritious food, bukan comfort food berlebihan. Fokus pada makanan rich in vitamins, protein untuk repair, dan anti-inflammatory foods.\n\n4. Listen to your body's signals. Demam, nyeri, atau fatigue adalah cara tubuh berkomunikasi. Jangan mask symptoms dengan medication tanpa address underlying cause.\n\n5. Create healing environment. Kamar yang bersih, cukup ventilasi, dan nyaman membantu pemulihan. Jangan underestimate power of good sleep environment.\n\n6. Know when to seek help. Jika symptoms persist lebih dari 3 hari, intensitas meningkat, atau ada red flag symptoms, jangan ragu konsultasi dokter. Early detection saves lives.\n\n7. Mental health affects physical recovery. Stress atau anxiety bisa menurunkan immune system. Practice relaxation techniques saat sakit.\n\nYour body is your permanent home. Take care of it.",
  makan: "Nutrisi yang baik mendukung kesehatan fisik dan mental. Konsumsi makanan bergizi seimbang dengan karbohidrat kompleks, protein, lemak sehat, vitamin, dan mineral. Jangan lupa minum air putih minimal 8 gelas sehari.",
  tidur: "Sleep adalah biological necessity, bukan luxury. Kualitas tidur yang buruk mempengaruhi segala aspek: mood, cognitive function, immune system, bahkan weight management. Berikut sleep hygiene yang terbukti:\n\n1. Consistent sleep schedule. Bangun dan tidur di jam yang sama setiap hari, termasuk weekend. Ini mengatur circadian rhythm Anda.\n\n2. Wind-down routine 30-60 menit sebelum tidur. Matikan gadget, coba stretching ringan, membaca buku fisik, atau meditasi. Blue light mengganggu melatonin production.\n\n3. Optimize sleep environment. Kamar harus gelap (gunakan blackout curtains), dingin (18-22°C ideal), dan tenang. Consider white noise machine jika environment bising.\n\n4. Limit caffeine dan heavy meals. Hindari kafein setelah jam 2 sore dan makanan berat 3 jam sebelum tidur. Digestion mengganggu sleep quality.\n\n5. Bed is for sleep only. Jangan kerja, nonton, atau scroll social media di tempat tidur. Ini membuat brain associate bed dengan wakefulness.\n\n6. Manage worry before bed. Jika pikiran berkecamuk, tulis di jurnal untuk 'park' thoughts sampai besok. Mindfulness atau progressive relaxation bisa membantu.\n\n7. Nap strategically. Jika perlu siang, batasi 20-30 menit sebelum jam 3 sore. Long naps atau late naps mengganggu nighttime sleep.\n\nSleep is the foundation of health. Protect it fiercely.",
  olahraga: "Movement adalah medicine yang paling powerful dan accessible. Regular exercise tidak hanya untuk physical fitness, tapi juga mental health, cognitive function, dan longevity. Berikut cara membuatnya sustainable:\n\n1. Find your why beyond aesthetics. Fokus pada energy, mood, strength, atau longevity daripada sekadar penampilan. Intrinsic motivation lasts longer.\n\n2. Start ridiculously small. 5 menit jalan kaki lebih baik dari rencana 1 jam gym yang tidak terlaksana. Build habit dulu, intensity menyusul.\n\n3. Choose enjoyable activities. Jika benci gym, jangan paksa. Coba dance, hiking, swimming, martial arts, atau olahraga tim. Enjoyment drives consistency.\n\n4. Schedule seperti meeting. Block waktu di calendar dan treat sebagai non-negotiable appointment dengan diri sendiri.\n\n5. Incorporate movement into daily life. Naik tangga, berdiri saat meeting, jalan kaki untuk meeting, atau stretching breaks setiap jam. NEAT (Non-Exercise Activity Thermogenesis) penting.\n\n6. Recovery is part of training. Jangan olahraga setiap hari tanpa rest. Sleep, nutrition, dan active recovery sama pentingnya dengan workout itu sendiri.\n\n7. Track progress untuk motivation. Catat improvements: bisa jalan lebih jauh, angkat lebih berat, atau sekadar mood yang lebih baik. Progress adalah motivator terbaik.\n\nThe best workout is the one you'll actually do consistently.",
  diet: "Diet sehat adalah tentang pola makan berkelanjutan, bukan pembatasan ekstrem. Fokus pada makanan utuh (whole foods), kontrol porsi, dan hindari makanan olahan berlebihan. Perubahan perlahan lebih bertahan lama.",
  gemuk: "Berat badan sehat adalah tentang keseimbangan, bukan angka tertentu. Fokus pada kebiasaan sehat: makan bergizi, olahraga teratur, tidur cukup, dan kelola stres. Hasil akan mengikuti prosesnya.",
  kurus: "Untuk menambah berat badan, fokus pada makanan padat nutrisi dan kalori sehat seperti kacang-kacangan, alpukat, dan protein. Kombinasikan dengan latihan kekuatan untuk membangun massa otot.",
  kulit: "Kesehatan kulit dimulai dari dalam: cukup tidur, minum air, makanan bergizi, dan proteksi sinar matahari. Rutinitas perawatan kulit yang sederhana namun konsisten lebih baik dari produk mahal.",
  mental: "Kesehatan mental sama pentingnya dengan kesehatan fisik. Jangan ragu mencari bantuan profesional jika dibutuhkan. Berbicara dengan psikolog bukan tanda kelemahan, melainkan keberanian.",

  // Pekerjaan & Karir
  kerja: "Meningkatkan produktivitas kerja bukan tentang bekerja lebih lama, melainkan bekerja lebih cerdas. Berikut strategi proven untuk performa optimal:\n\n1. Eat the frog first. Kerjakan tugas paling sulit dan penting di pagi hari ketika willpower masih penuh. Menunda tugas besar justru membuat anxiety seharian.\n\n2. Time-blocking technique. Jadwalkan setiap jam di calendar Anda dengan blok spesifik untuk task tertentu. Ini mengurangi decision fatigue dan context-switching yang boros energi.\n\n3. Pomodoro untuk deep work. 25 menit fokus tanpa distraksi, lalu break 5 menit. Setelah 4 cycle, break 15-30 menit. Timer membuat kita accountable.\n\n4. The 2-minute rule. Kalau sesuatu bisa dikerjakan dalam 2 menit, lakukan sekarang. Jangan biarkan small tasks menumpuk jadi beban mental.\n\n5. Eliminate distractions. Matikan notifikasi non-urgent, gunakan website blocker, dan komunikasikan ke rekan kerja tentang 'focus hours' Anda.\n\n6. Learn to say no. Setiap 'yes' terhadap task baru adalah 'no' terhadap task existing. Prioritaskan berdasarkan impact, bukan urgensi semata.\n\n7. Rest is productive. Productivity decreases setelah 50-60 jam kerja seminggu. Breaks, hiburan, dan tidur cukup justru membuat Anda lebih kreatif dan efisien.\n\nProductivity is about being effective, not busy. Focus on outcomes, not hours logged.",
  karir: "Career development adalah marathon, bukan sprint. Membangun karir yang fulfilling membutuhkan strategi jangka panjang, continuous learning, dan adaptabilitas. Berikut framework untuk pertumbuhan karir yang sustainable:\n\n1. Self-assessment yang jujur. Identifikasi strengths, weaknesses, values, dan interests Anda. Karir yang cocok adalah intersection antara what you're good at, what you love, dan what the world needs.\n\n2. Set clear career goals. Gunakan framework 3-5-10 tahun: posisi apa dalam 3 tahun? Industry apa dalam 5 tahun? Legacy apa dalam 10 tahun? Goals yang jelas membantu decision-making.\n\n3. Invest dalam skill building. Hard skills (technical) membuat Anda hired, soft skills (communication, leadership) membuat Anda promoted. Keduanya penting untuk long-term success.\n\n4. Find mentors and sponsors. Mentor memberi advice dan guidance; sponsors membuka doors dan advocate untuk Anda. Keduanya krusial untuk accelerasi karir.\n\n5. Build your personal brand. Showcase expertise melalui writing, speaking, atau contributing to projects. Reputasi yang kuat membuka opportunity tanpa Anda harus apply.\n\n6. Network strategically. Quality over quantity. Bangun relasi yang genuine dan mutually beneficial, bukan transactional connections.\n\n7. Take calculated risks. Pindah role, switch industry, atau ambil challenging assignment. Comfort zone adalah enemy of growth.\n\nCareer success is about direction, not speed.",
  wawancara: "Interview adalah sales process di mana produknya adalah Anda. Persiapan yang matang bisa membuat perbedaan antara 'meh' candidate dan 'must hire'. Berikut strategi untuk interview yang sukses:\n\n1. Research secara mendalam. Pahami company culture, recent news, products, competitors, dan challenges mereka. Gunakan LinkedIn untuk riset interviewer.\n\n2. Master the STAR method. Untuk behavioral questions (Tell me about a time when...), gunakan Situation-Task-Action-Result. Specificity adalah kunci.\n\n3. Prepare your value proposition. Apa yang membuat Anda unique? Highlight 3-4 key strengths dengan bukti konkrit. Jangan generic seperti 'saya rajin'.\n\n4. Anticipate tough questions. Siapkan jawaban untuk: weaknesses, gap dalam resume, kenapa pindah, dan salary expectations. Jangan defensive, be honest dengan growth mindset.\n\n5. Ask insightful questions. Interview adalah two-way street. Tanyakan tentang team dynamics, success metrics, growth opportunities, atau challenges dalam role tersebut.\n\n6. Practice out loud. Rehearse dengan teman atau di depan mirror. Record diri Anda untuk lihat body language dan filler words (um, like, you know).\n\n7. Follow up dengan gratitude email. Send personalized thank-you note dalam 24 jam, referensi spesifik dari conversation, dan reiterate interest.\n\nRemember: You are interviewing them as much as they are interviewing you.",
  resign: "Keputusan resign harus dipertimbangkan matang. Evaluasi alasan Anda, pastikan memiliki rencana keuangan dan rencana selanjutnya. Jaga profesionalisme saat proses pengunduran diri.",
  bisnis: "Membangun bisnis membutuhkan riset pasar, perencanaan finansial, dan kesabaran. Mulailah dari yang kecil, validasi ide Anda, dan siap untuk belajar dari kegagalan.",
  gaji: "Negosiasi gaji adalah hal yang wajar. Siapkan data gaji pasar untuk posisi Anda, highlight pencapaian dan kontribusi Anda, dan pilih waktu yang tepat untuk berdiskusi dengan atasan.",
  atasan: "Menjalin hubungan baik dengan atasan penting untuk karir. Komunikasikan progress secara rutin, minta feedback untuk berkembang, dan tunjukkan sikap proaktif dalam bekerja.",

  // Pendidikan & Belajar
  belajar: "Lifelong learning adalah competitive advantage di era yang berubah cepat. Effective learning bukan tentang menghabiskan waktu paling banyak, melainkan menggunakan strategi yang terbukti secara kognitif. Berikut science-based learning techniques:\n\n1. Active recall, not passive re-reading. Test yourself secara aktif daripada membaca ulang. Flashcards, practice tests, atau menjelaskan konsep ke orang lain lebih efektif.\n\n2. Spaced repetition. Review materi pada interval yang meningkat (1 hari, 3 hari, 1 minggu, 1 bulan). Ini memperkuat neural pathways lebih baik daripada cramming.\n\n3. Interleaving practice. Jangan latihan satu topik terus-menerus. Campur berbagai tipe problems untuk memaksa otak adaptasi dan membedakan konsep.\n\n4. Elaborative interrogation. Tanyakan 'why' dan 'how' secara konstan. Hubungkan konsep baru dengan knowledge yang sudah ada.\n\n5. Concrete examples. Abstract concepts lebih mudah dipahami dengan contoh konkrit dan real-world applications.\n\n6. Dual coding. Kombinasikan words dengan visuals (diagrams, mind maps, sketches). Otak memproses informasi visual lebih efisien.\n\n7. Teach others. The protégé effect: mengajar orang lain memaksa Anda menguasai materi lebih dalam dan mengidentifikasi gaps dalam understanding.\n\nLearning is not about time spent, but about strategies used.",
  ujian: "Persiapan ujian sebaiknya dilakukan jauh-jauh hari dengan belajar rutin. Hindari begadang sebelum ujian. Teknik flashcard dan latihan soal bisa membantu memperkuat pemahaman.",
  skripsi: "Penyusunan skripsi butuh manajemen waktu yang baik. Buat timeline dengan milestone jelas, konsultasikan secara rutin dengan dosen pembimbing, dan mulai dari yang paling mudah untuk membangun momentum.",
  kuliah: "Pengalaman kuliah adalah waktu untuk eksplorasi dan pengembangan diri. Selain akademik, ikuti organisasi atau kegiatan ekstrakurikuler untuk membangun soft skill dan relasi.",
  sekolah: "Masa sekolah adalah fondasi penting. Selain nilai, fokus juga pada pembentukan karakter, kebiasaan belajar, dan pengembangan minat. Jangan terlalu tertekan dengan perbandingan dengan teman.",
  bahasa: "Belajar bahasa baru membutuhkan konsistensi. Praktikkan setiap hari meski hanya 15 menit. Gunakan aplikasi, tonton film, atau cari partner bahasa untuk latihan percakapan.",

  // Keuangan
  uang: "Personal finance adalah life skill yang tidak diajarkan di sekolah, tapi berdampak besar pada quality of life. Financial wellbeing bukan tentang income tertinggi, melainkan management terbaik. Berikut framework yang terbukti:\n\n1. Track every expense. Awareness adalah langkah pertama. Gunakan apps atau spreadsheet untuk mencatat semua pengeluaran selama 30 hari. You'll be surprised where your money actually goes.\n\n2. Apply the 50/30/20 rule sebagai starting point. 50% untuk needs (housing, food, transport), 30% untuk wants (entertainment, dining out), 20% untuk savings dan debt repayment. Sesuaikan dengan situasi Anda.\n\n3. Build emergency fund dulu. Prioritaskan 3-6 bulan pengeluaran di savings yang accessible. Ini adalah safety net untuk unexpected events seperti job loss atau medical emergency.\n\n4. Automate your savings. Set automatic transfer di payday. Jika Anda tidak melihat uangnya, Anda tidak akan mengeluarkannya. Pay yourself first.\n\n5. Manage debt strategically. List semua utang dengan interest rates. Prioritaskan bayar high-interest debt (credit cards) lebih dulu sambil membayar minimum untuk lainnya.\n\n6. Diversify income streams. Relying on satu sumber income adalah risky. Explore side hustles, passive income, atau investasi untuk financial security.\n\n7. Invest in financial education. Baca buku personal finance, follow reputable financial advisors, dan terus belajar tentang money management.\n\nFinancial freedom is a journey, not a destination.",
  tabungan: "Menabung sebaiknya dilakukan rutin meski jumlah kecil. Automatisasi transfer ke rekening tabungan setelah gajian. Miliki dana darurat minimal 3-6 bulan pengeluaran.",
  investasi: "Investasi adalah cara membuat uang bekerja untuk Anda. Mulailah dengan risiko rendah seperti reksadana atau obligasi. Pelajari dasar-dasar dan sesuaikan dengan profil risiko Anda.",
  utang: "Kelola utang dengan bijak. Prioritaskan bayar utang dengan bunga tinggi terlebih dahulu. Hindari menambah utang konsumtif. Jika terlilit banyak utang, konsultasikan dengan ahli keuangan.",

  // Teknologi
  hp: "Penggunaan gadget yang bijak penting untuk kesehatan. Batasi screen time, gunakan mode gelap, perhatikan jarak pandang ke layar, dan ambil istirahat setiap 20 menit penggunaan.",
  laptop: "Rawat laptop dengan rutin bersihkan debu, update sistem operasi, dan hindari overcharging. Backup data penting secara rutin ke cloud atau external storage.",
  aplikasi: "Pilih aplikasi yang benar-benar membantu produktivitas, bukan malah mengganggu. Review dan hapus aplikasi yang jarang digunakan. Atur notifikasi untuk mengurangi gangguan.",

  // Rumah Tangga & Relasi
  hubungan: "Hubungan yang sehat didasari komunikasi terbuka tanpa menuduh, saling menghargai perbedaan, dan memberi ruang untuk masing-masing berkembang. Jangan takut diskusi tentang ekspektasi.",
  pacar: "Dalam pacaran, komunikasi jujur dan trust adalah fondasi. Jangan kehilangan identitas diri dan tetap jalani hobi serta pertemanan di luar hubungan.",
  nikah: "Pernikahan adalah komitmen jangka panjang yang butuh persiapan matang. Selain cinta, pertimbangkan kesesuaian nilai, tujuan hidup, dan kematangan emosional kedua belah pihak.",
  keluarga: "Keluarga adalah dukungan sistem yang penting. Luangkan waktu berkualitas meski sederhana seperti makan bersama. Komunikasi terbuka dengan anggota keluarga perlu dijaga.",
  orangtua: "Menjadi orang tua adalah perjalanan belajar tanpa akhir. Tiap anak unik, jadi hindari perbandingan. Waktu bersama yang berkualitas lebih berharga dari materi.",
  anak: "Pendidikan anak terbaik adalah dengan teladan. Ajarkan nilai-nilai positif, kemandirian, dan empati sejak dini. Dukung minat dan bakat alami mereka tanpa memaksakan.",
  saudara: "Hubungan dengan saudara adalah iklang seumur hidup. Meski ada perbedaan, usahakan menjaga komunikasi dan saling support dalam suka maupun duka.",
  tetangga: "Hubungan baik dengan tetangga menciptakan lingkungan yang nyaman. Hormati privasi masing-masing, tapi tetap sapa dan bantu jika dibutuhkan.",
  teman: "Pertemanan yang tulus saling mendukung tanpa bersyarat. Jaga kontak meski hanya sesekali, dan hadir saat teman membutuhkan. Kualitas lebih penting dari kuantitas.",

  // Pengembangan Diri
  motivasi: "Tetap termotivasi memang tidak selalu mudah, terutama saat menghadapi tantangan atau rasa lelah. Berikut beberapa cara efektif untuk menjaga motivasi:\n\n1. Tetapkan tujuan yang jelas dan pecah menjadi langkah kecil. Milestone yang achievable membuat Anda merasa progress.\n\n2. Ingat 'why' Anda - alasan kuat di balik tujuan tersebut. Reconnect dengan purpose bisa menyalakan kembali semangat.\n\n3. Kelilingi diri dengan support system positif. Teman, keluarga, atau mentor yang supportive bisa menjadi fuel motivasi.\n\n4. Rayakan small wins. Setiap pencapaian, sekecil apa pun, layak diapresiasi sebagai bukti kemajuan.\n\n5. Self-care adalah investasi, bukan pengkhianatan. Istirahat yang cukup justru membuat Anda lebih produktif dan fokus.\n\n6. Visualisasikan kesuksesan. Bayangkan diri Anda telah mencapai tujuan - feeling itu bisa mendorong action.\n\n7. Belajar dari kegagalan sebagai stepping stone, bukan dead end. Setiap orang sukses punya koleksi kegagalan di belakangnya.\n\nIngat, motivasi bukan sesuatu yang selalu ada 100%. Ada hari where you just need to show up dan lakukan yang terbaik meski tidak sempurna. Consistency beats intensity.",
  target: "Tetapkan target SMART: Specific, Measurable, Achievable, Relevant, Time-bound. Pecah target besar menjadi milestone kecil yang bisa diceklist. Rayakan setiap pencapaian.",
  sukses: "Sukses adalah definisi pribadi. Bukan tentang materi atau validasi orang lain, melainkan pencapaian tujuan yang Anda tetapkan dan kebahagiaan dalam prosesnya.",
  bahagia: "Kebahagiaan bukan tujuan akhir melainkan hasil dari kebiasaan positif dan mindset yang tepat. Bersyukur, relasi bermakna, dan hidup sesuai nilai adalah komponen pentingnya.",
  percaya: "Kepercayaan diri dibangun dari pengalaman. Mulailah dengan tantangan kecil, akui kemajuan Anda, dan jangan biarkan kegagalan masa lalu mendefinisikan kemampuan Anda.",
  introvert: "Introvert bukan kelemahan. Anda punya kekuatan dalam mendengarkan, berpikir mendalam, dan membangun relasi bermakna. Honor kebutuhan waktu sendiri untuk recharge.",

  // Spiritual & Filosofis
  agama: "Spiritualitas adalah perjalanan pribadi. Dalami ajaran agama Anda dengan hati terbuka, praktikkan nilai-nilai kebaikan, dan hormati perbedaan keyakinan orang lain.",
  makna: "Makna hidup sering ditemukan dalam pelayanan kepada orang lain, pencapaian pribadi, relasi bermakna, atau kreativitas. Eksplorasi apa yang memberi rasa puas bagi Anda.",
  mati: "Pemikiran tentang kematian bisa membuat kita menghargai hidup lebih dalam. Fokus pada apa yang bisa Anda kontrol sekarang: bagaimana Anda hidup dan berdampak pada orang lain.",

  // Lainnya
  cuaca: "Cuaca memang bisa mempengaruhi mood. Saat hujan, ciptakan suasana nyaman di rumah dengan minuman hangat dan aktivitas menyenangkan. Saat panas, tetap terhidrasi dan pakai sunscreen.",
  bencana: "Saat menghadapi bencana, prioritaskan keselamatan diri dan keluarga. Ikuti instruksi pihak berwenang, siapkan emergency kit, dan jaga komunikasi dengan keluarga.",
  politis: "Berpartisipasi dalam politik adalah hak dan tanggung jawab warga negara. Pelajari platform kandidat secara objektif, hindari hoax, dan gunakan hak pilih dengan bijak.",
  transport: "Transportasi umum mengurangi kemacetan dan polusi. Rencanakan perjalanan dengan cek rute dan jadwal terlebih dahulu. Selalu prioritaskan keselamatan di jalan.",
  liburan: "Liburan penting untuk recharge dan mendapat perspektif baru. Rencanakan dengan matang, tapi sisakan ruang untuk spontanitas. Dokumentasikan momen indahnya.",
  kado: "Memberi kado adalah ekspresi perhatian. Pilih sesuatu yang personal dan sesuai minat penerima. Bukan tentang harga, melainkan pemikiran di baliknya.",

  // Topik Umum Tambahan
  waktu: "Manajemen waktu adalah keterampilan penting. Gunakan teknik time-blocking, prioritaskan tugas berdasarkan urgensi dan kepentingan, dan hindari multitasking yang justru menurunkan efisiensi.",
  skill: "Pengembangan skill membutuhkan 10.000 jam latihan yang terstruktur. Fokus pada deliberate practice: berlatih di zona nyaman Anda, dapatkan feedback, dan perbaiki kelemahan secara spesifik.",
  komunikasi: "Komunikasi efektif melibatkan mendengarkan aktif, berbicara dengan jelas dan singkat, dan memperhatikan bahasa tubuh. Empati adalah fondasi komunikasi yang bermakna.",
  networking: "Membangun networking profesional dimulai dari memberi nilai lebih dulu. Hadir di event industri, gunakan LinkedIn dengan bijak, dan jaga relasi dengan follow-up yang tulus.",
  presentasi: "Presentasi yang baik dimulai dari persiapan matang. Kenali audiens Anda, struktur konten dengan jelas, gunakan visual minimalis, dan latih delivery hingga percaya diri.",
  memasak: "Memasak adalah keterampilan hidup yang berharga. Mulai dengan resep sederhana, investasi pada peralatan dasar berkualitas, dan jangan takut eksperimen dengan bumbu.",
  kopi: "Kopi yang nikmat membutuhkan perhatian pada biji berkualitas, grind size yang tepat, suhu air 90-96°C, dan ratio 1:15. Eksplorasi metode brewing manual untuk pengalaman berbeda.",
  membaca: "Kebiasaan membaca membuka wawasan dan meningkatkan fokus. Tetapkan target realistis, pilih buku sesuai minat, dan gunakan teknik skimming untuk buku non-fiksi.",
  menulis: "Menulis adalah keterampilan yang diasah dengan latihan rutin. Tulis setiap hari meski sedikit, fokus pada clarity bukan perfection, dan baca karya penulis hebat sebagai inspirasi.",
  musik: "Musik memiliki efek terapeutik yang terbukti secara ilmiah. Eksplor berbagai genre, coba belajar alat musik, atau gunakan playlist untuk berbagai aktivitas dan mood.",
  film: "Film adalah medium storytelling yang powerful. Selain hiburan, analisis struktur narasi dan teknik sinematik bisa mengasah apresiasi dan pemahaman visual.",
  fotografi: "Fotografi memadukan teknis dan artistry. Kuasai exposure triangle, komposisi rule of thirds, dan cahaya alami. Latih mata untuk melihat moment yang menarik.",
  traveling: "Traveling mengembangkan empati dan pemahaman budaya. Riset destinasi, respek tradisi lokal, coba kuliner autentik, dan biarkan spontanitas mengarahkan petualangan.",
  hewan: "Memelihara hewan mengajarkan tanggung jawab dan empati. Pahami kebutuhan spesies, siapkan komitmen jangka panjang, dan pertimbangkan adopsi dari shelter.",
  tanaman: "Berkebun mengurangi stres dan menghasilkan oksigen. Pilih tanaman sesuai kondisi cahaya rumah, atur jadwal penyiraman, dan nikmati proses pertumbuhannya.",
  minimalis: "Gaya hidup minimalis bukan tentang membuang segalanya, melainkan menyimpan hanya yang memberi nilai. Mulai dari declutter satu area, tanyakan apakah barang itu dibutuhkan atau disukai.",
  lingkungan: "Aksi kecil berdampak besar bagi lingkungan. Kurangi plastik sekali pakai, pilah sampah, pilih transportasi ramah lingkungan, dan dukung brand dengan praktik berkelanjutan.",
  volunteer: "Volunteer memberi makna dan koneksi komunitas. Pilih organisasi yang sejalan dengan nilai Anda, mulai dengan komitmen kecil, dan lihat dampak positif yang terwujud.",
  hobby: "Hobi penting untuk keseimbangan hidup dan kreativitas. Invest waktu pada aktivitas yang membuat Anda flow, tanpa tekanan untuk sempurna atau menghasilkan.",
  keamanan: "Keamanan digital mulai dari password kuat yang unik tiap akun, aktifkan two-factor authentication, hati-hati phishing, dan update software secara rutin.",

  // Teknologi & Digital Tambahan
  ai: "AI adalah alat bantu yang powerful. Gunakan untuk brainstorming, drafting, atau riset, tapi tetap verifikasi fakta dan pertahankan human judgment untuk keputusan penting.",
  coding: "Belajar coding dari nol memang menantang tapi sangat memungkinkan. Berikut roadmap efektif untuk pemula:\n\n1. Pilih satu bahasa pemrograman (Python untuk AI/data, JavaScript untuk web, atau Java untuk enterprise). Jangan belajar banyak bahasa sekaligus - fokus dulu satu sampai confident.\n\n2. Kuasai fundamentals: variable, data types, control flow, function, dan object-oriented. Dasar yang kuat akan memudahkan belajar bahasa lain nanti.\n\n3. Practice over theory. Untuk setiap konsep yang dipelajari, langsung tulis kode. Gunakan platform seperti LeetCode (algoritma), freeCodeCamp (project-based), atau Codecademy (interactive).\n\n4. Buat proyek kecil yang personally meaningful. Kalau suka film, buat movie tracker. Suka masak, buat recipe app. Motivasi lebih tinggi kalau membuat sesuatu yang Anda gunakan sendiri.\n\n5. Gabung komunitas: Discord server programming, local meetup, atau forum. Belajar bareng membuat journey lebih enjoyable dan dapat mentorship.\n\n6. Debugging adalah skill, bukan keberuntungan. Saat stuck, trace error message, Google spesifik, dan jangan takut bertanya di Stack Overflow dengan format yang jelas.\n\n7. Consistency beats intensity. 30 menit setiap hari lebih efektif dari 5 jam sekali seminggu. Build habit coding di jam yang sama setiap hari.\n\nRemember: Every expert was once a beginner. Jangan bandingkan diri dengan programmer senior yang sudah 10 tahun berpengalaman.",
  website: "Membuat website bisa dimulai dengan platform no-code seperti WordPress/Wix, atau belajar HTML/CSS/JavaScript untuk kustomisasi penuh.",
  data: "Data literacy penting di era digital. Pelajari Excel dasar, lalu SQL untuk database, atau Python (pandas) untuk analisis lebih dalam.",

  // Keseharian & Praktis
  resep: "Masak sendiri lebih sehat dan hemat. Cari resep dengan rating tinggi, ikuti step-by-step, dan jangan takut modifikasi sesuai selera.",
  cuci: "Mencuci pakaian dengan benar: pisahkan warna, perhatikan label care, gunakan deterjen sesuai takaran, dan jemur di tempat teduh agar awet.",
  bersih: "Kebersihan ruangan mempengaruhi produktivitas. Buat jadwal cleaning rutin, declutter regularly, dan gunakan storage yang terorganisir.",
  dekor: "Dekorasi ruangan tidak harus mahal. Manfaatkan secondhand, DIY, dan pilih tema warna konsisten untuk kesan cohesive.",

  // Kesehatan Mental & Self-Care
  meditasi: "Meditasi 10 menit sehari bisa mengubah struktur otak. Gunakan aplikasi guided seperti Headspace, atau mulai dengan fokus pada napas.",
  jurnal: "Journaling membantu processing emosi. Tulis 3 hal yang disyukuri setiap pagi, atau curahkan pikiran tanpa sensor sebelum tidur.",
  boundaries: "Boundary yang sehat itu perlu. Belajar mengatakan 'tidak' tanpa rasa bersalah, dan komunikasikan ekspektasi dengan jelas.",
  burnout: "Burnout bukan kelemahan. Tanda: cynicism, exhaustion, inefficacy. Solusi: rest, reconnect dengan purpose, dan evaluasi workload.",

  // Finansial Lanjut
  freelance: "Freelance menawarkan fleksibilitas tapi butuh disiplin. Atur jam kerja tetap, pisahkan rekening pribadi-bisnis, dan bayar pajak tepat waktu.",
  sidehustle: "Side hustle idealnya berawal dari hobi atau skill yang sudah dikuasai. Validasi demand dulu, baru invest waktu/duit.",
  pasif: "Income pasif membutuhkan upfront effort besar dulu: buat digital product, affiliate marketing, atau investasi dividen.",
  pajak: "Pahami kewajiban pajak Anda. Simpan bukti pengeluaran yang bisa diklaim, dan pertimbangkan konsultasi akuntan untuk optimalisasi legal.",

  // Relasi Sosial
  conflict: "Konflik adalah normal dalam relasi. Fokus pada issue bukan personal attack, cari win-win solution, dan tahu kapan untuk agree to disagree.",
  toxic: "Relasi toxic membuat Anda merasa drained. Tanda: constant criticism, lack of support, gaslighting. Prioritaskan mental health Anda.",
  single: "Masa single adalah kesempatan untuk self-discovery. Bangun foundation yang kuat: karir, hobby, support system, sebelum mencari partner.",
  moveon: "Moving on bukan tentang melupakan, melainkan menerima. Allow yourself to grieve, cut contact kalau perlu, dan fokus rebuild life Anda.",

  // Karir Development
  promosi: "Dapatkan promosi dengan consistently deliver di atas ekspektasi, bangun visibility di organisasi, dan develop leadership skills.",
  pindah: "Pindah kerja bisa refresh karir. Pertimbangkan: growth opportunity, culture fit, dan compensation package secara total.",
  remote: "Kerja remoto butuh self-discipline. Setup dedicated workspace, komunikasikan dengan tim secara rutin, dan jaga batasan work-life.",
};

function findResponse(context, responses) {
  const lowerContext = context.toLowerCase();
  for (const [keyword, response] of Object.entries(responses)) {
    if (lowerContext.includes(keyword)) {
      return response;
    }
  }
  return null;
}

function generateMockCaption({ context }) {
  const cleanedContext = typeof context === "string" ? context.trim() : "";

  if (!cleanedContext) {
    return "Silakan ajukan pertanyaan atau ceritakan apa yang Anda butuhkan. Saya siap membantu dengan informasi yang saya miliki.";
  }

  // Cari response berdasarkan keyword
  const matchedResponse = findResponse(cleanedContext, ID_RESPONSES);

  if (matchedResponse) {
    return matchedResponse;
  }

  // Template response yang mengakui topik user untuk pertanyaan tidak terduga
  const topicWords = cleanedContext.split(/\s+/).slice(0, 3).join(" ");

  // Respons generik tapi kontekstual yang mengakui input user
  const genericResponses = [
    `Terima kasih telah berbagi tentang "${topicWords}". Meski saat ini layanan AI penuh, saya mengerti hal ini penting bagi Anda. Coba telusuri sumber terpercaya atau diskusikan dengan ahli di bidang tersebut.`,
    `Saya memahami Anda bertanya tentang "${topicWords}". Ini adalah topik yang menarik. Saat layanan AI kembali normal, saya bisa memberikan informasi lebih detail. Untuk saat ini, silakan cari referensi dari buku atau artikel terpercaya.`,
    `Anda menanyakan hal yang penting tentang "${topicWords}". Setiap pertanyaan layak mendapat jawaban yang baik. Mohon maaf saat ini sistem dalam mode terbatas. Coba ulangi pertanyaan nanti atau eksplorasi berbagai perspektif tentang topik ini.`,
    `Pertanyaan Anda tentang "${topicWords}" menunjukkan rasa ingin tahu yang bagus. Pengetahuan memang terus berkembang. Saat ini layanan sedang tidak tersedia penuh, tapi jangan berhenti mencari tahu dari sumber lain yang kredibel.`,
  ];

  // Pilih respons generik secara random
  const randomIndex = Math.floor(Math.random() * genericResponses.length);
  return genericResponses[randomIndex];
}

module.exports = {
  generateMockCaption,
};

